name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - nonprod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with unittest
        run: |
          python -m unittest discover

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Set environment variables
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }} #loads secrets into env variables
          nonprod_deploy_url: ${{ secrets.NONPROD_RENDER_DEPLOY_HOOK }}
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "DEPLOY_URL=$deploy_url" >> "$GITHUB_ENV"
          else
              echo "DEPLOY_URL=$nonprod_deploy_url" >> "$GITHUB_ENV"
          fi
      - name: Deploy to server
        run: |
          curl "$DEPLOY_URL"
